name: 'mocha teste'

on:
  workflow_dispatch:

jobs:
  mocha_teste :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando mocha
        run: npm install -D mocha


