name: 'Mocha Teste'

on:
  workflow_dispatch: # Permite rodar manualmente
jobs:
  mocha_teste:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o seu repositório para a máquina virtual do Actions
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura a versão do Node.js que será usada
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use uma versão LTS (Long Term Support) do Node

      # 3. Instala todas as dependências do projeto listadas no package.json
      #- name: Instalar dependências
      #  run: npm ci
      - name: Instalando mocha
        run: npm install -D mocha 

      # 4. Roda o arquivo de teste específico dentro da pasta 'testes'
      - name: Rodar testes com Mocha
        run: npx mocha testes/teste.js